### PR TITLE
2048 demo

### PR DESCRIPTION
**Pull request by Raynos**
This is a tracking branch for the 2048 example.

### CODE REVIEW

**Comment by kumavis** [comment]
@Raynos is this good to merge?

**Comment by Raynos** [comment]
This one is not, @Matt-Esch had a branch with more progress i think.

**Comment by kuraga** [comment]
https://github.com/Matt-Esch/mercury/compare/2048-wip

**Comment by kuraga** [comment]
@Matt-Esch can you comment please? I've start your game, nice work :smile: What's incomplete?

**Comment by Raynos** [comment]
@kuraga good question.

I think it's not feature complete with the 2048 game. http://gabrielecirulli.github.io/2048/

Maybe we should merge it as is, it needs a rebase though :)

**Comment by kuraga** [comment]
@Raynos rebased version: https://github.com/kuraga/mercury/compare/Raynos:master...matt-esch

But there are many linting errors...

**Comment by Raynos** [comment]
So it'll need some cleanup, fair enough.

**Comment by Raynos** [comment]
most of the linting warnings are probably lack of use strict.

**Comment by kuraga** [comment]
See #153 instead now

**Comment by kumavis** [comment]
@kuraga ok to close this one?

**Pull request closed without merging**
