### PR TITLE
I made you a simple logo

### PR DESCRIPTION
**Pull request by nbostrom**
I read in your roadmap that you're planning on creating a logo for the project, so I decided to create one.
I wasn't sure if you are referring to the planet or the metal. I chose to create one that resembles the metal since I really wanted to include the M. That was easier to do with the metal than the planet. I also tried to make it look friendly and simple. An advanced logo for a project like this could make people think of complexity and scare them away.

If you like it, feel free to pull it in. If you don't, well don't. I don't mind at all. It's WTFPL-licensed ;)

### CODE REVIEW

**Comment by clearjs** [comment]
A few drafts with different fonts for the original proposal: https://github.com/clearjs/mercury-logo

**Comment by Raynos** [comment]
cool :)

**Comment by clearjs** [comment]
Also I'd probably drop the .js extension.

**Comment by rawberg** [comment]
+1 for the @nrw version

**Comment by kumavis** [comment]
i like @nrw 's block version, but the full one not as much.
@ahdinosaur's oribtal, planetary theme is nice

I really like the hexagon-shaped space-themed ones in the [io.js logo brainstorm](https://github.com/iojs/io.js/issues/37)

**Comment by kumavis** [comment]
@clearjs i was in a small town in peru recently and i saw a sign for some small shop, and it immediately made me think of your mercury logo. it was a funny connection.

**Comment by neonstalwart** [comment]
@nrw's block one is also my favorite - a variation could be to put "hg" rather than "m".

**Comment by clearjs** [comment]
@kumavis The original logo is made by @nbostrom, I just tried minor font variations.

**Comment by kumavis** [comment]
whoops!

**Comment by jonnyscholes** [comment]
+1 for @nrw's one - in terms of use as an asset in a larger design I think it will be great to work with :)

**Comment by twilson63** [comment]
Here is another logo suggestion:

mercury

**Comment by kumavis** [comment]
not mine but heres a different direction
speaks to mercury's speed and unobtrusive lightweight nature
image

**Comment by danielnaab** [comment]
I like all these logos, but just had a thought to share. What about something with Mercury, the god? The caduceus is usually shown in Mercury's hands in most images: 
- https://en.wikipedia.org/wiki/Caduceus
- https://www.google.com/search?q=mercury&espv=2&biw=1055&bih=755&source=lnms&tbm=isch&sa=X&ei=dl6EVeqMMpCuogS2oILQDw&ved=0CAYQ_AUoAQ#tbm=isch&q=mercury+god

Loosely, unidirection is implied by the spirals of the snakes wrapping around themselves.

I've always like the style of O'Reilly's book covers, and Flask's logo is in a similar style and might be an inspiration on how to stylize it (http://flask.pocoo.org).

**Comment by kumavis** [comment]
@danielnaab yes that was the direction I was headed -- I think it is a great source of iconography-- the caduceus is interesting, id like to explore the visual metaphors there

**Comment by martinpallmann** [comment]
I really like the caduceus.

**Comment by ashnur** [comment]
+1 for caduceus

**Comment by sartaj** [comment]
+1 for @ahdinosaur

**Comment by eightyeight** [comment]
+1 for @sartaj

**Comment by eightyeight** [comment]
@twilson63 I like the concept, but I think the sheer number of arrows is too much. I'd use the same font and colour but put the `Hg` inside a circle with a single arrow on it somewhere.

**Comment by twilson63** [comment]
@eightyeight Thanks how about this -> http://codepen.io/twilson63/pen/pjRqvm

**Comment by eightyeight** [comment]
@twilson63 I don't see a ton of difference. I do think a nicer font would be in order, but I didn't want to go looking. Also I just realised that the text is black inside; that was a mistake, it should have been grey like all the strokes!

[Riffing on the planetary theme](http://jsfiddle.net/DFhUF/2537/)

**Comment by ashnur** [comment]
I am not a fan of spelling out `Hg` and the association with the element.

**Comment by eightyeight** [comment]
+1 @1j01

**Comment by 1j01** [comment]
-2 @1j01

**Comment by activestylus** [comment]
Designer of Merb and Slim logos/sites here. I love helping out awesome open source projects get a proper makeover. Hope that this community can decide soon - proper branding is CRUCIAL for a framework to gain mindshare

mercury

**Comment by ashnur** [comment]
@activestylus option 1 is the first from all which I really like :)

**Comment by activestylus** [comment]
Thanks for the feedback @ashnur - I agree the 1st one makes it look more "pro" and less like a toy.

For further edification here is how a proper homepage could conceivably look.

image

What say you @Raynos? Mercury has a decent following without any promotion or even something that could pass for a project homepage, so kudos on that. But I think you will get a lot more exposure and community once you create your online image, get a short manifesto up and put some love on those docs.

**Comment by nrw** [comment]
i'm in for @activestylus option 1

**Comment by DeepAnchor** [comment]
@activestylus those are awesome. I'm also partial towards option #1 myself, though maybe a lighter shade of grey like in that last logo you posted would lighten the mood a little bit. Dark grey brings to mind serious, enterprisy stuff imo

**Comment by yoshuawuyts** [comment]
Hex logo in the style of `leveldb`, `sheetify`, `stack.gl` and `scijs`:
__tiny__
mercury logo

__large__


Figure consistent branding to some degree might help with cross-polination between ecosystems.

**Comment by roobie** [comment]
There's two things I like with @yoshuawuyts contribution:

1. The first thing I related it to was the CPU for a model T-1000 Terminator
2. It looks like my mental model of how components fit together in a bigger system.

/2¢

**Pull request closed without merging**
