### PR TITLE
Update virtual-dom

### PR DESCRIPTION
**Pull request by gcallaghan**
I ran the tests with the new dependency and verified that *my* application ran as expected. I'm not sure if there is something else that is needed.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
if tests are passing, and you've tested it in a real world application I think this should be :+1:

**Comment by nlocnila** [comment]
+1

**Comment by eightyeight** [comment]
Wow, I thought there was supposed to be a lot more fuss.

**Comment by gcallaghan** [comment]
Can this get merged? Is there more I should do?

**Comment by ashnur** [comment]
I think it would be great to confirm if all the examples work.

**Comment by gcallaghan** [comment]
Great point! It crossed my mind before the 9-5 demanded my attention. I'll get on it.

**Comment by gcallaghan** [comment]
Updated commit to include more dependencies and verified that all the examples work when https://github.com/maxogden/javascript-editor/issues/11 is resolved.

**Comment by Raynos** [comment]
:-1: We do not update all dependencies in one commit.

If certain dependencies have to be updated, we update them ideally one by one or groups at a time.

**Comment by gcallaghan** [comment]
fair enough. I'll reduce the scope of the commit.

**Comment by Raynos** [comment]
```
npm http fetch GET https://github.com/tmcw/CodeMirror/archive/module-export.tar.gz
npm http fetch 404 https://github.com/tmcw/CodeMirror/archive/module-export.tar.gz
npm ERR! fetch failed https://github.com/tmcw/CodeMirror/archive/module-export.tar.gz
```

This sucks :(

**Comment by gcallaghan** [comment]
@raynos, that's why I opened the related pull request first

**Comment by gcallaghan** [comment]
Reduced the scope of the commit to only include virtual-dom

**Comment by Raynos** [comment]
Last time i tried to upgrade virtual-dom it broke the examples. 

Someone has to check the examples work locally and really play around with them.

**Comment by gcallaghan** [comment]
I ran the examples with a locally linked javascript-editor package. They all seem to work. No errors in the console and content updates as I would expect. If something is broken it's definitely not obvious. Anything to look for in particular?

**Comment by Raynos** [comment]
@gcallaghan the only thing to look for the is the TodoMVC example; play around with it for editing, adding, removing.

**Comment by gcallaghan** [comment]
TODO MVC example works except for the clear completed, however, this is broken on master as well.

**Comment by Raynos** [comment]
Clear completed in this build ( http://raynos.github.io/mercury/examples/todomvc/index.html ) seems to work ok.

**Comment by gcallaghan** [comment]
I'll take a look to see why my local build is different

**Comment by gcallaghan** [comment]
There's a difference on the build you pointed me to @Raynos 

The hosted build has the following function which works.

    function clearCompleted(state) {
       state.todos().forEach(function (todo, index) {
            if (todo.completed) {
                destroy(state, todo)
            }
        })
    }

Master contains the following code, that I receive when running `npm run examples` 

    function clearCompleted(state) {
        Object.keys(state.todos).forEach(function clear(key) {
            if (TodoItem.isCompleted(state.todos[key])) {
                destroy(state, state.todos[key]());
            }
        });
    }

This breaks because 'set' is returned as a key of  state.todos.

I think this is unrelated to this pull request.

**Comment by Raynos** [comment]
Let's just get this in; fix forward anything else we find :)

**Comment by Raynos** [comment]
14.1.0

**Pull request merged**
