### PR TITLE
Examples npm script fixed.

### PR DESCRIPTION
**Pull request by lucianlature**
Fixed a bug where each example was `undefined` in content due to not correctly being set.

### CODE REVIEW

**Comment by Raynos** [comment]
This depends completely on the version of `routes-router`.

Can you `npm install routes-router --save` and update the package.json & verify it again ?

**Comment by lucianlature** [comment]
Installed the latest version of `routes-router` initially and this is how I've noticed the bug in the first phase. So, yes, I've verified it again and it needs `opts.params.name` instead of `opts.name`.

**Comment by Raynos** [comment]
The latest version of routes-router is version 4. Can you update the package.json ?

**Comment by lucianlature** [comment]
@Raynos: Since https://github.com/Raynos/routes-router is deprecated, wouldn't be beneficial on the longer term to use https://github.com/Matt-Esch/http-hash-router instead?

**Comment by kuraga** [comment]
Yes and remove `examples/lib/router`.

**Comment by Raynos** [comment]
@lucianlature yeah, feel free to fix that in this PR or in another PR.

Refactoring examples/lib/router into mercury-router is out of scope for this PR, but feel free to open a seperate PR for that.

**Comment by kumavis** [comment]
@lucianlature is this PR good to go?

**Comment by lucianlature** [comment]
@kumavis: Yep :+1:

**Comment by Raynos** [comment]
if it works then #coolstory #shipit

**Pull request merged**
