### PR TITLE
Add example of hot reloading with browserify/watchify

### PR DESCRIPTION
**Pull request by martintietz**
This basically adds an example of hot reloading with browserify (extends the work already done in #180).

### CODE REVIEW

**Comment by Raynos** [comment]
Looks legit.

You have any opinions @eightyeight  ?

**Comment by yoshuawuyts** [comment]
ooh, neat! +1

**Comment by eightyeight** [comment]
Looks good to me. Thanks @martintietz for completing the example! Might be nice to add it to the main readme as well, maybe under intermediate examples.

**Comment by Raynos** [comment]
o/

**Pull request merged**
