### PR TITLE
Development improvements

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by Raynos** [comment]
Mostly looks good. Let's keep lint-trap though

**Comment by kuraga** [comment]
Updated. There are some `lint-trap` issues

**Comment by kuraga** [comment]
We can also use original `synthetic-dom-events` after defunctzombie/synthetic-dom-events#8 will be merged

**Comment by Raynos** [comment]
@kuraga feel free to land on master. ill unbreak it.

**Comment by Raynos** [comment]
@kuraga I fixed all the errors, see the latest commit on master.

I didnt fix the warnings, although they are easy to fix, it just means that `{ foo: 'bar' }` becomes

```js
{
  foo: 'bar'
}
```

`lint-trap` is enforcing that we dont cheat with one line objects.

**Comment by kuraga** [comment]
Thanks!

**Pull request merged**
