### PR TITLE
Add missing jquery dep for example

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by Raynos** [comment]
This is a good joke. I appreciate this.

**Comment by aredridel** [comment]
The example does require it :)

**Comment by Raynos** [comment]
Which one :( I'm pretty sure we only use virtual-dom or React in examples.

**Comment by aredridel** [comment]
Okay now I feel like I'm going crazy. I tracked this down but now it's working. Well then sorry for the noise.

**Comment by Raynos** [comment]
No worries; thanks for opening a PR though.

**Comment by coballast** [comment]
There is an example that requires jquery. When I run npm run build:

```
 npm run build

> mercury@14.0.0 build /home/colin/mercury
> node bin/build.js

reading /home/colin/mercury/examples/geometry/browser.js
reading /home/colin/mercury/examples/todomvc/browser.js
reading /home/colin/mercury/examples/markdown/browser.js
reading /home/colin/mercury/examples/number-input/browser.js
reading /home/colin/mercury/examples/unidirectional/backbone/browser.js
reading /home/colin/mercury/examples/unidirectional/jsx/browser.js
reading /home/colin/mercury/examples/unidirectional/immutable/browser.js
reading /home/colin/mercury/examples/login-form/browser.js
reading /home/colin/mercury/examples/bmi-counter.js
reading /home/colin/mercury/examples/shared-state.js
reading /home/colin/mercury/examples/count.js
reading /home/colin/mercury/examples/canvas.js
reading /home/colin/mercury/examples/async-state.js
reading /home/colin/mercury/examples/real-dom.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: module "jquery" not found from "/home/colin/mercury/node_modules/backbone/backbone.js"
    at notFound (/home/colin/mercury/node_modules/browserify/index.js:803:15)
    at /home/colin/mercury/node_modules/browserify/index.js:754:23
    at /home/colin/mercury/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
    at /home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:44:14
    at process (/home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:113:43)
    at /home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:122:21
    at load (/home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:54:43)
    at /home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:60:22
    at /home/colin/mercury/node_modules/browserify/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/home/colin/.nvm/versions/node/v4.2.1/bin/node" "/home/colin/.nvm/versions/node/v4.2.1/bin/npm" "run" "build"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! mercury@14.0.0 build: `node bin/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mercury@14.0.0 build script 'node bin/build.js'.
npm ERR! This is most likely a problem with the mercury package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mercury
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/colin/mercury/npm-debug.log
```

**Comment by aredridel** [comment]
YES! That was it!

**Comment by Raynos** [comment]
Oh I see; looks like we do need jquery (backboooooooooooone).

**Comment by Raynos** [comment]
We can add that to dev deps.

**Comment by Raynos** [comment]
Our friend @coballast fixed this :) thanks.

**Pull request closed without merging**
